# Target specific macros

TARGET = stephanie
TARGET_SOURCES = \
	src/stephanie.c \
	$(wildcard src/lib/*.c)	
TOPPERS_OSEK_OIL_SOURCE = ./src/stephanie.oil

BUILD_MODE = RXE_ONLY

# Don't modify below part
O_PATH ?= build
include /group/osek/nxtOSEK/ecrobot/ecrobot.mak