# Target specific macros

TARGET = madeleine
TARGET_SOURCES = \
	src/madeleine.c \
	$(wildcard src/lib/*.c)
TOPPERS_OSEK_OIL_SOURCE = ./src/madeleine.oil

BUILD_MODE = RXE_ONLY

# Don't modify below part
O_PATH ?= build
include /group/osek/nxtOSEK/ecrobot/ecrobot.mak